### ISSUE TITLE
graphql.config.yml is missing

### ISSUE THREAD

**Issue by DavidDeSloovere** [datocms/ecommerce-website-demo#1]
I notice the `graphql.config.yml` file is missing. Probably the same as https://github.com/datocms/next-landing-page-demo/blob/main/graphql.config.yml ?

PS: In our project we defined the config in .ts file, so we can read the API key from env. As a example/template, might be better use this approach to show how it can be done more securely.

**Comment by marcelofinamorvieira** [comment]
Added in https://github.com/datocms/ecommerce-website-demo/commit/0ed98cb75e70f439ea9dc753d3268195f151fba4 

Thank you @DavidDeSloovere !
